project_id = "gaaxslezqzzujfrtkdpo"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-question-series]
    verify_jwt = false
  [functions.generate-facebook-ideas]
    verify_jwt = false
  [functions.search-facebook-trends]
    verify_jwt = false
