project_id = "gaaxslezqzzujfrtkdpo"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-video-topics]
    verify_jwt = true
  [functions.generate-script]
    verify_jwt = true
