const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, topics } = await req.json();

    if (!email || !topics || !Array.isArray(topics)) {
      return new Response(
        JSON.stringify({ success: false, error: 'email and topics array are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Invalid email address' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const resendKey = Deno.env.get('RESEND_API_KEY');
    if (!resendKey) {
      return new Response(
        JSON.stringify({ success: false, error: 'Email service not configured. Please add RESEND_API_KEY.' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Build HTML email
    const topicListHtml = topics.map((t: { keyword: string; ideas: string[] }, i: number) => `
      <div style="margin-bottom: 20px; padding: 16px; background: #f8f7ff; border-radius: 8px; border-left: 3px solid #6366f1;">
        <h3 style="margin: 0 0 8px; color: #1a1a1a; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">${i + 1}. ${t.keyword}</h3>
        <ul style="margin: 0; padding-left: 16px;">
          ${t.ideas.map(idea => `<li style="color: #333; font-size: 14px; margin-bottom: 6px;">▶ ${idea}</li>`).join('')}
        </ul>
      </div>
    `).join('');

    const html = `
      <div style="max-width: 600px; margin: 0 auto; font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a;">
        <div style="text-align: center; padding: 32px 0 16px;">
          <h1 style="margin: 0; font-size: 24px; color: #1a1a1a;">☠️ Funeral Trends</h1>
          <p style="margin: 8px 0 0; color: #666; font-size: 14px;">Your Top 10 Video Topic Ideas</p>
        </div>
        <div style="padding: 0 16px;">
          ${topicListHtml}
        </div>
        <div style="text-align: center; padding: 24px 16px; color: #999; font-size: 12px; border-top: 1px solid #eee; margin-top: 16px;">
          Generated by Funeral Trends Dashboard · ${new Date().toLocaleDateString()}
        </div>
      </div>
    `;

    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Funeral Trends <onboarding@resend.dev>',
        to: [email],
        subject: '🎬 Your Top 10 Funeral Video Topic Ideas',
        html,
      }),
    });

    if (!resendResponse.ok) {
      const errText = await resendResponse.text();
      console.error('Resend error:', errText);
      return new Response(
        JSON.stringify({ success: false, error: 'Failed to send email' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error sending email:', error);
    return new Response(
      JSON.stringify({ success: false, error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
